#! /bin/sh
# Copy HTML which differ into html_docs
set -e

outdir=html_docs
base_branch=$1

mkdir "$outdir"
cp new-docs/src/sgml/html/*.css new-docs/src/sgml/html/*.svg "$outdir"

# The index is useful to allow a static link to the artifacts for the most-recent, successful CI run for a branch
# https://api.cirrus-ci.com/v1/artifact/github/USERNAME/postgres/Documentation/html_docs/html_docs/00-doc.html?branch=BRANCH
index="$outdir/00-doc.html"
echo "<html><head><title>Index of docs changed since: $base_branch</title></head><body><ul>" >"$index"

changed=`git diff --no-index --name-only old-docs/src/sgml/html new-docs/src/sgml/html` ||
	[ $? -eq 1 ]

for f in $changed
do
	cp "$f" "$outdir"
	fn=${f##*/}
	# ?branch=... is needed for the static link for the branch
	# It's not used if accessing artifacts for *this* CI run
	echo "<li><a href='$fn?branch=$base_branch'>$fn</a>"
done >>"$index"

echo "</ul></body></html>" >>"$index"
