#! /bin/sh
set -e

## this script makes some assumptions about the formatting of files it parses.
## in postgresql.conf.sample:
##   1) the valid config settings may be preceded by a '#', but NOT '# '
##      (we use this to skip comments)

### What options are listed in postgresql.conf.sample, but don't appear
### in guc.c?

# grab everything that looks like a setting
SETTINGS=`sed '/^#[[:alnum:]]/!d; s/^#//; s/ =.*//; /^include/d' postgresql.conf.sample`

for i in $SETTINGS ; do
  ## it sure would be nice to replace this with an sql "not in" statement
  grep -i "\"$i\"" guc.c >/dev/null ||
    echo "$i seems to be missing from guc.c";
done

### What options are listed in guc.c, but don't appear
### in postgresql.conf.sample?

# grab everything that looks like a setting and convert it to lower case
SETTINGS=`gawk -F '[",]' 'BEGIN{RS="\n\t\\\\{\n"} /",[[:space:]]*PGC_.*.*gettext_noop/ && !/NOT_IN_SAMPLE/{print tolower($2)}' guc.c`
for i in $SETTINGS ; do
  grep "#$i " postgresql.conf.sample >/dev/null ||
    echo "$i seems to be missing from postgresql.conf.sample";
done
