#!/usr/bin/env python3

import os
import shutil
import subprocess
import sys

src_dir = sys.argv[1]
build_dir = sys.argv[2]
llvm_lto = sys.argv[3]
output_dir = os.path.realpath(sys.argv[5])
index = output_dir + '/postgres.index.bc'
private_dir = sys.argv[6]
file_names = sys.argv[7:]
dest_dir = output_dir + '/postgres'

# Remove old contents if exist
if os.path.exists(dest_dir):
  shutil.rmtree(dest_dir)

shutil.copytree(os.path.realpath(private_dir), dest_dir)

# Change working directory for irlink to link correctly
os.chdir(output_dir)

file_names = ['postgres' + input.replace(private_dir, '') for input in file_names]
command = '{} -thinlto -thinlto-action=thinlink -o {} {}'.format(llvm_lto, index, ' '.join(file_names))
subprocess.run(command, shell=True)
